---
title: "Section_2_2_text"
author: "Philippe Glaziou"
date: "`r Sys.Date()`"
output:
  html_fragment:
  # Don’t include a table of contents
    toc: no
# Set standard figure width to 12 inches
    fig_width: 12
# Don’t write figure captions
    fig_caption: FALSE
---


```{r setup, include=FALSE}
# Section 1
# Set options, load data, utility functions

knitr::opts_chunk$set(echo = FALSE,
                      results = "asis",
                      message = FALSE,
                      warning = FALSE)
library(data.table)
library(here)

load(here('report/data/gtb.rda'))

```


```{css, echo=FALSE}

/* Styles to make it easier to see in the html_fragment; this CSS can be included in the CSS widget of Sitefinity */
  
.section.level3 {
  padding-bottom: 1em;
  border-bottom: 1px solid #BCBCBC;
  margin-bottom: 2em;
}


.subhead, .footnote {
  font-size: 80%;
  font-weight: normal;
  margin-top: 0;
  padding-top: 0;
}

.red, .red a {
  color: #F21905; /* red text to show figure number */
}

div {
  text-align: justify;
  text-justify: inter-word;
  
}

.textbox {
    width: 100%;
    background-color: #daeef4;
    font-family: Arial, Helvetica, sans-serif;
    text-align: justify;
    text-justify: inter-word;
    padding: 15px;
}

```


## 2.2 TB mortality

Tuberculosis (TB) is preventable and curable, and some countries have already reduced their burden of TB disease to fewer than 10 cases and less than 1 death per 100 000 population per year (<span style="color:#F21905;"><strong>Section 2.1</strong></span>).  Globally and in many countries, however, TB remains a leading or major cause of ill-health and mortality. 

The World Health Organization (WHO) End TB Strategy includes global targets and milestones for substantial reductions in the annual number of TB deaths between 2016 and 2035. The first milestone is a 35% reduction by 2020 compared with 2015. The next 2025 milestone is a 75% reduction compared with 2015, followed by targets for reductions of 90% by 2030 and 95% by 2035. Reaching these milestones and targets requires achievement of global milestones and targets for reductions in the number of people who develop TB each year (<span style="color:#F21905;"><strong>Section 2.1</strong></span>) and reductions in the case fatality ratio (CFR; the percentage of people with TB who die from the disease). The global CFR needed to fall to 10% by 2020 and then to 6.5% (a level already achieved in high-income countries) by 2025. The latter can only be achieved if everyone who develops TB can access high-quality TB treatment. 

Based on the international classification of diseases (ICD), deaths from TB among HIV-negative people are classified as TB deaths (<i>1</i>). When an HIV-positive person dies from TB, the underlying cause is classified as HIV with TB as a contributory cause. For consistency with international classifications, this section makes a clear distinction between TB deaths in HIV-negative people and TB deaths in HIV-positive people. The milestones and targets for reductions in TB deaths set in the End TB Strategy are for the combined total of deaths in HIV-positive and HIV-negative people. 

Estimates of the number of TB deaths in 2020 should be regarded as provisional (<span style="color:#F21905;"><strong>Box 2.2.1</strong></span>). They suggest that the global number of TB deaths increased between 2019 and 2020: from `r ftb(global$mort.nh.num[20]/1e6)` million (95% uncertainty interval [UI], `r ftb(global$mort.nh.lo.num[20]/1e6)`–`r ftb(global$mort.nh.hi.num[20]/1e6)` million) to `r ftb(global$mort.nh.num[21]/1e6)` million (UI, `r ftb(global$mort.nh.lo.num[21]/1e6)`–`r ftb(global$mort.nh.hi.num[21]/1e6)` million) among HIV-negative people and from `r ftb(global$mort.h.num[20])` (UI, `r ftb(global$mort.h.lo.num[20])`–`r ftb(global$mort.h.hi.num[20])`) to `r ftb(global$mort.h.num[21])` (UI, `r ftb(global$mort.h.lo.num[21])`–`r ftb(global$mort.h.hi.num[21])`) among HIV-positive people (<span style="color:#F21905;"><strong>Table 2.2.1</span></strong>, `r lnk("Fig. 2.2.1")`). This is the first annual increase in the number of people dying from TB since 2005. It has been caused by disruptions to provision of and access to essential TB diagnostic and treatment services during the COVID-19 pandemic, which have resulted in an `r ftb(100 * (1 - global$c.newinc[21]/global$c.newinc[20]))`% reduction in the number of people reported to have been diagnosed with TB in 2020 (<span style="color:#F21905;"><strong>Section 1</strong></span>, <span style="color:#F21905;"><strong>Section 3</strong></span>). The global CFR in 2020 was `r ftb(100*global$cfr[21])`%, up from `r ftb(100*global$cfr[20])`% in 2019.

The impact of the COVID-19 pandemic has reversed years of global progress in reducing the number of people who die from TB, with the estimated number of deaths in 2020 back to the level of 2017 (`r lnk("Fig. 2.2.1")`). Instead of the targeted 35% reduction in the number of TB deaths between 2015 and 2020, there was a reduction of only `r ftb(100*(1-global$mort.num[21]/global$mort.num[16]))`%.  Projections of TB mortality that account for the impact of the COVID-19 pandemic in 16 priority countries which accounted for `r ftb(est[year==yr, sum(inc.num), by=(iso3 %in% unique(model$iso3))][, V1/(sum(V1))][2]*100)`% of the total number of people who fell ill with TB in 2020 (including two of the top three, India and Indonesia) suggest that the global number of TB deaths could rise further in 2022 and 2023 (<span style="color:#F21905;"><strong>Section 1</strong></span>), in line with earlier modelling projections (<i>5–8</i>). 

The latest year for which WHO has published estimates of global deaths by cause is 2019 (`r lnk("Fig. 2.2.2")`). These estimates showed that TB was the top cause of death from a single infectious agent and the 13th leading cause of death worldwide. In 2020, it is anticipated that TB will rank second as a cause of death from a single infectious agent, after COVID-19 (<i>4</i>). The estimated number of deaths officially classified as caused by TB (`r ftb(last(global$mort.nh.num)/1e6)` million) in 2020 was almost double the number caused by HIV/AIDS (`r ftb(est[year==2020, sum(mort.hiv.num, na.rm=T)]/1e6)` million), and TB mortality was more severely impacted by the COVID-19 pandemic (`r lnk("Fig. 2.2.3")`, `r lnk("Fig. 2.2.4")`). In contrast to TB, deaths from HIV/AIDS continued to decline between 2019 and 2020 (<i>9</i>). 

The global pattern of a fall in the TB mortality rate (TB deaths per 100 000 population per year) and in the absolute number of TB deaths until 2019, followed by an increase in 2020, was evident in four of the six WHO regions; the exceptions were the African and Western Pacific regions, where there was a flat trend (`r lnk("Fig. 2.2.5")`, `r lnk("Fig. 2.2.6")`). The WHO European Region came closest to reaching the 2020 milestone of a 35% reduction in TB deaths between 2015 and 2020, with an estimated reduction of `r regional[g.whoregion=='EUR', ftb(100*(1-mort.num[21]/mort.num[16]))]`%. This decline was driven by progress in the Russian Federation, where the annual number of TB deaths fell 10% per year between 2010 and 2020. The African Region made relatively good progress, with a reduction of `r ftb(100*regional[g.whoregion=='AFR' & year %in% c(2015, 2020), 1-mort.num[2]/mort.num[1]])`%. In contrast, the number of TB deaths in 2020 was higher than in 2015 in two WHO regions: the Americas (+`r ftb(100*regional[g.whoregion=='AMR' & year %in% c(2015, 2020), mort.num[2]/mort.num[1]-1])`%), and the Western Pacific (+`r ftb(100*regional[g.whoregion=='WPR' & year %in% c(2015, 2020), mort.num[2]/mort.num[1]-1])`%). The declines compared with 2015 in the Eastern Mediterranean Region (`r ftb(100*regional[g.whoregion=='EMR' & year %in% c(2015, 2020), 1-mort.num[2]/mort.num[1]])`%) and South-East Asia (`r ftb(100*regional[g.whoregion=='SEA' & year %in% c(2015, 2020), 1-mort.num[2]/mort.num[1]])`%) were small.

The number of TB deaths increased in 2020 in most of the 30 high TB burden countries (`r lnk("Fig. 2.2.7a")`). Only `r int2word(hest[year==yr & mort.num<mort.milestone, .N])` high TB burden countries achieved the milestone of a 35% reduction between 2015 and 2020: `r setkey(hest, country);toString(hest[year==yr & mort.num<mort.milestone, country2][1:(hest[year==yr & mort.num<mort.milestone, .N] - 1)])` and `r last(hest[year==yr & mort.num<mort.milestone, country2])`. Of the three global TB watchlist countries, only the Russian Federation achieved the milestone (`r lnk("Fig. 2.2.7b")`), with a cumulative reduction of `r last(est[iso3 %in% c('RUS') & year>= 2015, ftb(100 * (1 - mort.num/mort.num[1]))])`%. In total, `r ftb(est[year==yr & mort.num<mort.milestone, .N])` countries reached the milestone. 

In 2020, about `r ftb(regional[year==yr, sum(mort.nh.num), by=g.whoregion %in% c('AFR','SEA')][,V1/sum(V1)][2] * 100)`% of TB deaths among HIV-negative people and `r ftb(regional[year==yr, sum(mort.num), by=g.whoregion %in% c('AFR','SEA')][,V1/sum(V1)][2] * 100)`% of the combined total of TB deaths in HIV-negative and HIV-positive people occurred in the WHO African and South-East Asia regions (<span style="color:#F21905;"><strong>Table 2.2.1</strong></span>). India accounted for `r ftb(est['IND',100*last(mort.nh.num)]/last(global$mort.nh.num))`% of global TB deaths among HIV-negative people, and for `r ftb(est['IND',100*last(mort.num)]/last(global$mort.num))`% of the combined total number of TB deaths in HIV-negative and HIV-positive people. There is considerable national variation in the TB mortality rate (`r lnk("Fig. 2.2.8")`) and the CFR (`r lnk("Fig. 2.2.9")`).

Globally in 2020, `r ftb(Mglobsplt[child==F & sex=='M',sum(mort) * 100])`% of the HIV-negative people who died from TB were men, `r ftb(Mglobsplt[child==F & sex=='F',sum(mort) * 100])`% were women and `r ftb(Mglobsplt[child==T,sum(mort)*100])`% were children (aged <15 years) (`r lnk("Fig. 2.2.10")`). The higher share for children compared with their estimated share of cases (`r ftb(globsplt[child==T,sum(inc)] * 100 / last(global$inc.num))`%) suggests poorer access to diagnosis and treatment. Of the TB deaths among HIV-positive people, `r ftb(MPglobsplit[sex=='M' & acat=='15+', deaths.pc])`% were men, `r ftb(MPglobsplit[sex=='F' & acat=='15+', deaths.pc])`% were women and `r ftb(MPglobsplit[acat!='15+', sum(deaths.pc)])`% were children.

Further country-specific details about estimates of the number of TB deaths and TB mortality rates are available in the [Global tuberculosis report app](https://www.who.int/teams/global-tuberculosis-programme/data/) and [online country profiles](https://worldhealthorg.shinyapps.io/tb_profiles/?_inputs_&entity_type=%22country%22&lan=%22EN%22&iso2=%22AF%22). 


<div class="textbox">
<strong><p>Box 2.2.1 </p></strong><br>
<strong><p>Methods used by WHO to estimate TB mortality</p></strong><br>

The main methods used by WHO to estimate TB mortality at country level in the period 2000–2019 and for 2020 specifically are shown in `r lnk("Fig. 2.2.11a")` and `r lnk("Fig. 2.2.11b")`. These methods adhere to global guidelines for accurate and transparent reporting of health estimates (<i>10</i>) and are described in detail in a [technical annex](https://who.int/teams/global-tuberculosis-programme/tb-reports/global-tuberculosis-report-2021/technicalannexes).

Estimates of the number of TB deaths among HIV-negative people published by WHO in 2020 for the period 2000–2019 used data on causes of death from national vital registration (VR) systems or mortality survey data for 123 countries (`r lnk("Fig. 2.2.11a")`), which collectively accounted for 60% of the estimated number of TB deaths (among HIV-negative people) globally in 2019 (<i>2</i>). For 21 of these countries, analyses of VR data and resulting estimates of TB deaths published by the Institute of Health Metrics and Evaluation (IHME) were used (<i>3</i>). For all other countries, TB mortality among HIV-negative people was estimated as the product of TB incidence and the CFR. For all countries, TB mortality among HIV-positive people was estimated as the product of TB incidence and the CFR, with the latter accounting for the protective effect of antiretroviral treatment (ART).

To estimate the number of TB deaths in 2020, new methods were required to account for the impact of the COVID-19 pandemic (`r lnk("Fig. 2.2.11b")`). Dynamic modelling was used for 16 priority countries and a statistical model was developed to extend these modelled estimates to `r ftb(est[year==yr & source.mort=='Predicted mortality ratio', .N])` other countries. VR data continued to be used for `r ftb(est[year==yr & source.mort=='VR', .N])` countries. Extrapolation of the pre-2020 trend was used for `r ftb(est[year==yr & source.mort=='Current trends', .N])` countries. All estimates for 2020 should be considered *provisional*. In addition to the need for further refinement of methods used for TB specifically, data on the total number of deaths in 2020 (including those with unknown or ill-defined causes) are required, but not yet available to WHO.  

</div>

<p><strong>References</strong></p>
<ol style="font-size:80%;">

<li>	International statistical classification of diseases and health related problems (The) ICD-10. Geneva: World Health Organization; 2016 (https://icd.who.int/browse10/2016/en).</li>

<li>	Global tuberculosis report 2020. Geneva, World Health Organization; 2020 (https://www.who.int/publications/i/item/9789240013131).</li>

<li>	GBD results tool [website]. Global Health Data Exchange; 2020 (http://ghdx.healthdata.org/gbd-results-tool).</li>

<li>	Coronavirus (COVID-19) dashboard. Geneva: World Health Organization. https://covid19.who.int/ </li>

<li>	Glaziou P. Predicted impact of the COVID-19 pandemic on global tuberculosis deaths in 2020. medRxiv 2020; 2020.04.28.20079582. </li>

<li>	Hogan AB, Jewell BL, Sherrard-Smith E, Vesga JF, Watson OJ, Whittaker C et al. Potential impact of the COVID-19 pandemic on HIV, tuberculosis, and malaria in low-income and middle-income countries: a modelling study. Lancet Glob Health 2020; 2020;8(9):e1132–e41. </li>

<li>	McQuaid CF, McCreesh N, Read JM, Sumner T, Houben RM, White RG et al. The potential impact of COVID-19-related disruption on tuberculosis burden. Eur Respir J 2020; 56(2). </li>

<li>	The potential impact of the COVID-19 response on tuberculosis in high-burden countries: a modelling analysis. Geneva: Stop TB Partnership in collaboration with Imperial College, Avenir Health, Johns Hopkins University and USAID; 2020 (http://stoptb.org/assets/documents/news/Modeling%20Report_1%20May%202020_FINAL.pdf). </li>

<li>	AIDS info [website]. 2021 (http://aidsinfo.unaids.org/). </li>

<li>	Guidelines for Accurate and Transparent Health Estimates Reporting (GATHER) [website]. Geneva: World Health Organization; 2021 (http://gather-statement.org/). </li>

</ol>
</p>

