---
title: "Section 4 TB prevention (text)"
author: "Hazim Timimi"
date: "`r Sys.Date()`"
output: 
  html_fragment:
    # Don’t include a table of contents
    toc: no
    # Set standard figure width to 12 inches
    fig_width: 12
    # Don’t write figure captions
    fig_caption: FALSE
---

```{r setup, include=FALSE}
# Set chunk options.
# Results "asis" is useful to output markdown from a function
# Suppress messages, warnings and also the ## at the beginning of printed text

knitr::opts_chunk$set(echo = FALSE, 
                      results = "asis",
                      message = FALSE,
                      warning = FALSE)

# Kill any attempt at using factors, unless we explicitly want them!
options(stringsAsFactors=FALSE)


# Load output packages ----
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
library(ggplot2)
library(dplyr)
library(scales)
library(RColorBrewer)
library(whomap)
library(gtbreport)
library(here)

# load section data
source(here('report/ch4-dataprep.r'))

# Function to override int_spacer() in the gtbreport package
# replace space with a non-breaking space so that numbers aren't spread over
# two lines 
int_spacer <- function(x){
  gsub(" ", "&nbsp;", gtbreport::int_spacer(x))
}



# Quick functions for callouts in the text to the figures/tables:

# 1. lnk() Creates a link from text to a named anchor)
lnk <- function(display_name){
  return(paste0('<span class="red">[', 
                display_name, 
                '](#', 
                gsub("[^a-zA-Z0-9]", "-", tolower(display_name)),
                ')</span>'))
}

# 2. anch() creates the named anchor to go above the figure or table
anch <- function(display_name){
  return(paste0('<a name="', 
                gsub("[^a-zA-Z0-9]", "-", tolower(display_name)),
                '"></a>'))
}

# 3. ref_lnk() creates a link from text to the references in the WHO style (black, italic)
ref_lnk <- function(display_name){
  return(paste0('<span class="refs">[', 
                display_name, 
                '](#refs)</span>'))
}


# rmarkdown::render(here::here("report/ch4-txt.rmd"), output_file = "ch4-txt.html", output_dir = here::here("report/html/"))

```


```{css, echo=FALSE}

/* Styles to make it easier to see in the html_fragment; this CSS can be included in the CSS widget of Sitefinity */
  
.section.level3 {
  padding-bottom: 1em;
  border-bottom: 1px solid #BCBCBC;
  margin-bottom: 2em;
}


.subhead, .footnote {
  font-size: 80%;
  font-weight: normal;
  margin-top: 0;
  padding-top: 0;
}

.red, .red a {
  color: #F21905; /* red text to show figure number */
  font-weight: bold;
}

.refs, .refs a {
  color: #3c4245;  /* match SF normal text colour */
  font-style: italic;
}

/* justify paragraphs to both left and right margins in the text under heading 2 */
.level2 p {
  text-align: justify;
  text-justify: inter-word;
}

```



# 4. TB prevention

_Draft! Prepared `r Sys.Date()` using country-reported data CSV files dated `r csv_datestamp` and estimates files dated  `r csv_estimate_datestamp`._


Preventing tuberculosis (TB) infection and stopping progression from infection to disease are critical to reduce TB incidence to the levels envisaged by the End TB Strategy. The main health care interventions to achieve this reduction are TB preventive treatment, which the World Health Organization (WHO) recommends for people living with HIV, household contacts of people with TB and other risk groups (`r ref_lnk("1")`); TB infection prevention and control; and vaccination of children with the bacille Calmette-Guérin (BCG) vaccine. Addressing broader determinants that influence TB epidemics can also help to prevent TB infection and disease; these are discussed in <span class="red">Section 6.3</span>.

At the first United Nations (UN) high-level meeting on TB in 2018, Member States committed to a global target of providing TB preventive treatment to at least 30 million people in the 5-year period 2018–2022: 6 million people living with HIV, 4 million children aged under 5 years who are household contacts of people diagnosed with TB, and 20 million household contacts in older age groups (`r ref_lnk("2")`). At the UN high-level meeting on HIV and AIDS held in June 2021, countries committed to ensuring that 90% of people living with HIV receive TB preventive treatment by 2025 (`r ref_lnk("3")`).

The global number of people living with HIV and household contacts of people diagnosed with TB who were provided with TB preventive treatment increased from `r ftb(f4.1_txt$tot_tpt_2015/1e6)` million in 2015 to `r ftb(f4.1_txt$tot_tpt_2019/1e6)` million in 2019, with a particularly large increase (`r ftb(f4.1_txt$delta_18_19/1e6)` million) between 2018 and 2019 (`r lnk("Fig. 4.1")`). However, this positive trend reversed between 2019 and 2020 (`r lnk("Fig. 4.1")`), probably reflecting disruptions to health services caused by the COVID-19 pandemic. The total number of people provided with TB preventive treatment in 2020 was `r ftb(f4.1_txt$tot_tpt_2020/1e6)` million, a `r ftb(f4.1_txt$pct_20_19)`%  reduction compared with 2019. Progress made in the past 3 years lags far behind that needed to reach the global target set at the UN high-level meeting on TB: the combined total of `r ftb(f4.1_txt$tot_tpt_18_20/1e6)` million in 2018–2020 is only `r ftb(f4.1_txt$pct_tpt_target)`% of the target of 30 million for the 5-year period 2018–2022 (`r lnk("Fig. 4.2")`).

Provision of TB preventive treatment to household contacts increased between 2015 and 2019 (`r lnk("Fig. 4.1")`) but fell from `r ftb(f4.1_txt$tot_con_tpt_2019/1e6)` million in 2019 to `r ftb(f4.1_txt$tot_con_tpt_2020/1e6)` million in 2020 (a reduction of `r ftb(f4.1_txt$con_20_19_pct)`%). The cumulative number of contacts initiated on TB preventive treatment in the 3-year period 2018–2020, at `r ftb(f4.2_txt$all_con/1e6)` million, is only `r ftb(f4.2_txt$all_con_target)`% of the target of 24 million for the 5-year period 2018–2022. This number included `r ftb(f4.2_txt$house_con04_tpt/1e6)` million children aged under 5 years (`r ftb(f4.2_txt$con04_target)`% of the 5-year target of 4 million) and `r ftb(f4.2_txt$house_con5plus_tpt/1e6)` million people in older age groups (`r ftb(f4.2_txt$con5plus_target)`% of the 5-year target of 20 million) (`r lnk("Fig. 4.2")`). 

Globally in 2020, `r ftb(f4.3_txt$newinc_con_2020/1e6)` million contacts of bacteriologically confirmed pulmonary TB cases were reported, of whom `r ftb(f4.3_txt$newinc_con_screen_2020/1e6)` million (`r ftb(f4.3_txt$screened_pct_2020)`%) were evaluated for both TB infection and disease. These numbers were decreases (of `r ftb(f4.3_txt$change_con_20_19_pct)`% and  `r ftb(f4.3_txt$change_screen_20_19_pct)`%, respectively) from the `r ftb(f4.3_txt$newinc_con_2019/1e6)` million reported and `r ftb(f4.3_txt$newinc_con_screen_2019/1e6)` million evaluated in 2019. Coverage of screening and initiation of TB preventive treatment varied widely among countries (`r lnk("Fig. 4.3")`, `r lnk("Fig. 4.4")`). There was also considerable variation in treatment completion rates. For the first time this year, countries reported TB preventive treatment completion data: among household contacts starting TB preventive treatment in 2019, the median completion rate was `r ftb(f4.5_txt$median)`% (IQR, `r ftb(f4.5_txt$q1)`–`r ftb(f4.5_txt$q3)`%) in `r f4.5_txt$countries` countries (`r lnk("Fig. 4.5")`).

Most of those provided with TB preventive treatment to date have been people living with HIV (`r lnk("Fig. 4.1")`). Globally, the annual number increased from fewer than 30&nbsp;000 in 2005 to `r ftb(f4.6_txt$hiv_tpt_2019/1e6)` million in `r report_year-2`, before falling to `r ftb(f4.6_txt$hiv_tpt_2020/1e6)` million in `r report_year-1`, a reduction of `r ftb(f4.6_txt$pct_20_19)`% compared with `r report_year-2` (`r lnk("Fig. 4.6")`). There were reductions in most WHO regions between 2019 and 2020. Six countries - `r knitr::combine_words(f4.7_txt_list$country, oxford_comma=FALSE)` - each reported initiating over `r int_spacer(2e5)` people with HIV on TB preventive treatment in `r report_year-1`,  accounting collectively for `r ftb(f4.7_txt$prop_top_6)`% of the `r ftb(f4.7_txt$hiv_tpt_glob/1e6)` million reported globally (`r lnk("Fig. 4.7")`). Between 2018 and `r report_year-1`, `r ftb(f4.6_txt$hiv_tpt_18_20/1e6)` million people with HIV received TB preventive treatment, meaning that the UN high-level meeting target of 6 million has been achieved well ahead of schedule. This represents a milestone achievement. However, accelerated scale-up will be needed to meet the implementation target of 90% by 2025, set out in the End TB Strategy and reaffirmed at the 2021 UN high-level Meeting on HIV and AIDS.

Between 2005 and the end of 2020, `r ftb(f4.6_txt$hiv_tpt_05_20/1e6)` million people living with HIV were initiated on TB preventive treatment, equivalent to about one third of the 37.7 million people estimated to be living with HIV in 2020 (`r ref_lnk("4")`). Coverage varies widely among countries: in `r int2word(f4.5_old_txt$countries)` high TB/HIV burden countries that reported data for 2020, the median coverage was `r ftb(f4.5_old_txt$median)`% (interquartile range [IQR], `r ftb(f4.5_old_txt$q1)`–`r ftb(f4.5_old_txt$q3)`%) among eligible people newly started on antiretroviral treatment. In `r completion_txt$countries` countries reporting data, a median of `r ftb(completion_txt$median)`% (IQR, `r ftb(completion_txt$q1)`–`r ftb(completion_txt$q3)`%) of people living with HIV who started TB preventive treatment in 2019 completed their treatment. This was the first time that these data were collected.

Reaching the targets for provision of TB preventive treatment set at UN high-level meetings in 2018 and 2021 will require a substantial intensification and expansion of efforts and investment, as highlighted by participants at a WHO high-level event convened in June 2021 (`r ref_lnk("5, 6")`). This will require more TB screening at household level (especially among people aged 5 years and over), strengthening the follow-up to TB screening at both household level and among people living with HIV, and increased access to shorter (1–3 months) rifamycin-based regimens. The implementation of new WHO recommendations on TB screening released in 2021 (<span class="red">Featured topic on TB guidelines</span>), and the WHO guidelines on TB preventive treatment, including recommendations on rifapentine-containing regimens, will help to achieve these targets. By June 2021, `r f4.8_txt$countries_used` countries reported that they had used shorter rifapentine-containing regimens (including trials and subnational projects), up from 29 one year earlier (`r lnk("Fig. 4.8")`). Action is now particularly urgent, given the serious disruptions to essential TB services caused by the COVID-19 pandemic since 2020 (<span class="red">Section 1</span>, <span class="red">Section 3</span>).

The risk of TB among health care workers relative to the risk in the general adult population is one of the indicators recommended by WHO for measuring the impact of interventions for TB infection prevention and control in health care facilities. If effective prevention measures are in place, the risk ratio for TB in health care workers compared with the general adult population should be close to 1. In 2020, `r int_spacer(f4.9_txt$tot_hcw_tb)` health care workers from `r f4.9_txt$countries_hcw_tb` countries were reported to have been diagnosed with TB. The ratio of the TB notification rate among health care workers to the general adult population was greater than 1 in `r f4.9_txt$countries_nrr` countries that reported five or more TB cases among health care workers (`r lnk("Fig. 4.9")`).

BCG vaccination is recommended as part of national childhood immunization programmes, in line with a country’s TB epidemiology. The most recent data (`r ref_lnk("7")`) indicate that `r f4.10_txt$countries_1` countries have a policy of BCG vaccination for the whole population, with `r bcg_txt$bcg_2020_gte95` of these countries reporting coverage of at least 95% (`r lnk("Fig. 4.10")`). In a further `r f4.10_txt$countries_2` countries, BCG vaccination is reserved for specific population groups. Of countries reporting BCG coverage data in 2019, `r bcg_txt$bcg_down_5` reported a reduction in coverage of 5% or more in 2020 compared with 2019; `r bcg_txt$no_rep_2020` did not report data. This decline was greater than that seen in previous years, and may reflect disruptions to health services caused by the COVID-19 pandemic.

Country-specific details are available in the [Global tuberculosis report app](https://www.who.int/teams/global-tuberculosis-programme/data/) and [country profiles](https://worldhealthorg.shinyapps.io/tb_profiles/).





`r anch("refs")`

**References**

<div class="footnote">

1. WHO consolidated guidelines on tuberculosis. Module 2: Screening – systematic screening for tuberculosis disease. Geneva: World Health Organization; 2021 (https://www.who.int/publications/i/item/9789240022676).
2. United Nations General Assembly. Resolution 73/3: Political declaration of the high-level meeting of the General Assembly on the fight against tuberculosis. New York: United Nations; 2018 (https://www.un.org/en/ga/search/view_doc.asp?symbol=A/RES/73/3).
3. United Nations General Assembly. 75th session. Item 10 of the agenda. Implementation of the Declaration of Commitment on HIV/AIDS and the political declarations on HIV/AIDS. Draft resolution submitted by the President of the General Assembly. Political Declaration on HIV and AIDS: Ending Inequalities and Getting on Track to End AIDS by 2030 (A/75/L.95). New York: United Nations; 2018 (https://www.un.org/pga/75/wp-content/uploads/sites/100/2021/06/2107241E1.pdf).
4.  Global HIV & AIDS statistics – fact sheet [website]. Geneva: UNAIDS; 2021 (https://www.unaids.org/en/resources/fact-sheet).
5. United Nations General Assembly. 75th session. Item 132 of the provisional agenda. Progress towards the achievement of global tuberculosis targets and implementation of the political declaration of the high-level meeting of the General Assembly on the fight against tuberculosis. Report of the Secretary-General (A/75/236). New York: United Nations; 2020 (https://undocs.org/en/A/75/236).
6. Call to Action 2.0: a global drive to scale up TB prevention. Geneva: World Health Organization; 2021 (https://www.who.int/publications/m/item/call-to-action-2.0-a-global-drive-to-scale-up-tb-prevention).
7. BCG – Immunization coverage estimates by country [website]. Geneva: World Health Organization; 2021 (https://www.who.int/data/gho/data/indicators/indicator-details/GHO/bcg-immunization-coverage-among-1-year-olds-(-)).

 
</div>

